# Generated by Django 4.0.3 on 2022-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_kakao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='phone_number',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
