# Generated by Django 4.0.3 on 2022-04-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_host_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='space_size',
            new_name='space',
        ),
    ]
